package com.kerebus.gn.level
{
	import com.kerebus.gn.Level;
	import com.kerebus.gn.LevelBackground;
	import com.kerebus.gn.LevelEvent;
	import com.kerebus.gn.MathUtils;
	import com.kerebus.gn.ObjectFactory;
	import com.kerebus.gn.ResourceManager;
	
	import flash.geom.Point;

	public class LevelTwo extends Level
	{
		public function LevelTwo(objectFactory : ObjectFactory)
		{
			super("Revenge of the ninja", objectFactory);
			
			setupLevel();
		}
		
		private function setupLevel() : void {
			background = new LevelBackground();			
			background.tileScrollRate = 25;
			background.tileHeight = 40;
			background.tileWidth = 40;
			background.tiles = 			
			[
				[
					[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID2, ResourceManager.GreenGraphicsID3]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID5, ResourceManager.GreenGraphicsID6]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID5, ResourceManager.GreenGraphicsID6]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID2, ResourceManager.GreenGraphicsID65, ResourceManager.GreenGraphicsID6]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID5, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID2, ResourceManager.GreenGraphicsID3, ResourceManager.GreenGraphicsID65, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6]
					,[ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID1, ResourceManager.GreenGraphicsID5, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6]
					,[ResourceManager.GreenGraphicsID3, ResourceManager.GreenGraphicsID3, ResourceManager.GreenGraphicsID3, ResourceManager.GreenGraphicsID3, ResourceManager.GreenGraphicsID3, ResourceManager.GreenGraphicsID3, ResourceManager.GreenGraphicsID3, ResourceManager.GreenGraphicsID3, ResourceManager.GreenGraphicsID3, ResourceManager.GreenGraphicsID3, ResourceManager.GreenGraphicsID65, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6]
					,[ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6]
					,[ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6]
					,[ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6]
					,[ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6]
					,[ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6]
					,[ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6, ResourceManager.GreenGraphicsID6]
				]
				,[
					[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]
					,[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]
					,[null, null, null, null, null, null, ResourceManager.GreenGraphicsID32, ResourceManager.GreenGraphicsID33, null, null, null, null, null, null, null]
					,[null, null, ResourceManager.GreenGraphicsID32, ResourceManager.GreenGraphicsID33, null, null, ResourceManager.GreenGraphicsID40, ResourceManager.GreenGraphicsID41, null, null, null, null, null, null, null]
					,[null, null, ResourceManager.GreenGraphicsID40, ResourceManager.GreenGraphicsID41, null, null, ResourceManager.GreenGraphicsID48, ResourceManager.GreenGraphicsID49, null, null, null, null, null, null, null]
					,[null, null, ResourceManager.GreenGraphicsID48, ResourceManager.GreenGraphicsID49, null, null, null, null, null, null, null, null, null, null, null]
					,[null, null, null, null, ResourceManager.GreenGraphicsID56, ResourceManager.GreenGraphicsID57, ResourceManager.GreenGraphicsID58, null, null, null, null, ResourceManager.GreenGraphicsID56, ResourceManager.GreenGraphicsID57, ResourceManager.GreenGraphicsID58, null]
					,[null, null, null, null, ResourceManager.GreenGraphicsID59, ResourceManager.GreenGraphicsID60, ResourceManager.GreenGraphicsID61, null, null, null, null, ResourceManager.GreenGraphicsID59, ResourceManager.GreenGraphicsID60, ResourceManager.GreenGraphicsID61, null]
					,[ResourceManager.GreenGraphicsID32, ResourceManager.GreenGraphicsID33, null, null, ResourceManager.GreenGraphicsID62, ResourceManager.GreenGraphicsID63, ResourceManager.GreenGraphicsID64, ResourceManager.GreenGraphicsID56, ResourceManager.GreenGraphicsID57, ResourceManager.GreenGraphicsID58, null, ResourceManager.GreenGraphicsID62, ResourceManager.GreenGraphicsID63, ResourceManager.GreenGraphicsID64, null]
					,[ResourceManager.GreenGraphicsID40, ResourceManager.GreenGraphicsID41, null, null, null, null, null, ResourceManager.GreenGraphicsID59, ResourceManager.GreenGraphicsID60, ResourceManager.GreenGraphicsID61, null, null, null, null, null]
					,[ResourceManager.GreenGraphicsID48, ResourceManager.GreenGraphicsID49, null, null, ResourceManager.GreenGraphicsID56, ResourceManager.GreenGraphicsID57, ResourceManager.GreenGraphicsID58, ResourceManager.GreenGraphicsID62, ResourceManager.GreenGraphicsID63, ResourceManager.GreenGraphicsID64, null, null, null, null, null]
					,[null, null, null, null, ResourceManager.GreenGraphicsID59, ResourceManager.GreenGraphicsID60, ResourceManager.GreenGraphicsID61, null, null, null, null, null, null, null, null]
					,[null, null, null, null, ResourceManager.GreenGraphicsID62, ResourceManager.GreenGraphicsID63, ResourceManager.GreenGraphicsID64, null, null, null, ResourceManager.GreenGraphicsID56, ResourceManager.GreenGraphicsID57, ResourceManager.GreenGraphicsID58, null, null]
					,[null, null, ResourceManager.GreenGraphicsID11, ResourceManager.GreenGraphicsID12, ResourceManager.GreenGraphicsID13, ResourceManager.GreenGraphicsID14, ResourceManager.GreenGraphicsID13, ResourceManager.GreenGraphicsID15, ResourceManager.GreenGraphicsID16, null, ResourceManager.GreenGraphicsID59, ResourceManager.GreenGraphicsID60, ResourceManager.GreenGraphicsID61, ResourceManager.GreenGraphicsID11, ResourceManager.GreenGraphicsID12]
					,[null, null, ResourceManager.GreenGraphicsID17, ResourceManager.GreenGraphicsID18, ResourceManager.GreenGraphicsID19, ResourceManager.GreenGraphicsID20, ResourceManager.GreenGraphicsID19, ResourceManager.GreenGraphicsID21, ResourceManager.GreenGraphicsID22, null, ResourceManager.GreenGraphicsID62, ResourceManager.GreenGraphicsID63, ResourceManager.GreenGraphicsID64, ResourceManager.GreenGraphicsID17, ResourceManager.GreenGraphicsID18]
					,[null, null, ResourceManager.GreenGraphicsID23, ResourceManager.GreenGraphicsID24, ResourceManager.GreenGraphicsID20, ResourceManager.GreenGraphicsID20, ResourceManager.GreenGraphicsID20, ResourceManager.GreenGraphicsID30, ResourceManager.GreenGraphicsID31, null, null, null, null, ResourceManager.GreenGraphicsID23, ResourceManager.GreenGraphicsID24]
					,[null, null, ResourceManager.GreenGraphicsID34, ResourceManager.GreenGraphicsID35, ResourceManager.GreenGraphicsID36, ResourceManager.GreenGraphicsID37, ResourceManager.GreenGraphicsID37, ResourceManager.GreenGraphicsID38, ResourceManager.GreenGraphicsID39, null, null, null, null, ResourceManager.GreenGraphicsID23, ResourceManager.GreenGraphicsID24]
					,[null, null, ResourceManager.GreenGraphicsID42, ResourceManager.GreenGraphicsID43, ResourceManager.GreenGraphicsID44, ResourceManager.GreenGraphicsID45, ResourceManager.GreenGraphicsID45, ResourceManager.GreenGraphicsID46, ResourceManager.GreenGraphicsID47, null, null, null, null, ResourceManager.GreenGraphicsID23, ResourceManager.GreenGraphicsID24]
					,[null, null, ResourceManager.GreenGraphicsID50, ResourceManager.GreenGraphicsID51, ResourceManager.GreenGraphicsID52, ResourceManager.GreenGraphicsID53, ResourceManager.GreenGraphicsID53, ResourceManager.GreenGraphicsID54, ResourceManager.GreenGraphicsID55, null, null, null, null, ResourceManager.GreenGraphicsID23, ResourceManager.GreenGraphicsID24]
					,[null, null, null, null, null, null, null, null, null, null, null, null, null, ResourceManager.GreenGraphicsID34, ResourceManager.GreenGraphicsID35]
					,[null, null, null, ResourceManager.GreenGraphicsID11, ResourceManager.GreenGraphicsID12, ResourceManager.GreenGraphicsID13, ResourceManager.GreenGraphicsID13, null, null, null, null, null, null, ResourceManager.GreenGraphicsID42, ResourceManager.GreenGraphicsID43]
					,[null, null, null, ResourceManager.GreenGraphicsID17, ResourceManager.GreenGraphicsID18, ResourceManager.GreenGraphicsID19, ResourceManager.GreenGraphicsID19, ResourceManager.GreenGraphicsID21, ResourceManager.GreenGraphicsID22, null, ResourceManager.GreenGraphicsID32, ResourceManager.GreenGraphicsID33, null, ResourceManager.GreenGraphicsID50, ResourceManager.GreenGraphicsID51]
					,[null, null, null, ResourceManager.GreenGraphicsID34, ResourceManager.GreenGraphicsID35, ResourceManager.GreenGraphicsID37, ResourceManager.GreenGraphicsID37, ResourceManager.GreenGraphicsID38, ResourceManager.GreenGraphicsID39, null, ResourceManager.GreenGraphicsID40, ResourceManager.GreenGraphicsID41, null, null, null]
					,[null, null, null, ResourceManager.GreenGraphicsID42, ResourceManager.GreenGraphicsID43, ResourceManager.GreenGraphicsID45, ResourceManager.GreenGraphicsID45, ResourceManager.GreenGraphicsID46, ResourceManager.GreenGraphicsID47, null, ResourceManager.GreenGraphicsID48, ResourceManager.GreenGraphicsID49, null, null, null]
					,[null, null, null, ResourceManager.GreenGraphicsID50, ResourceManager.GreenGraphicsID51, ResourceManager.GreenGraphicsID53, ResourceManager.GreenGraphicsID53, ResourceManager.GreenGraphicsID54, ResourceManager.GreenGraphicsID55, null, null, null, null, null, null]
					,[null, ResourceManager.GreenGraphicsID32, ResourceManager.GreenGraphicsID33, null, null, null, null, null, null, null, null, null, null, null, null]
					,[null, ResourceManager.GreenGraphicsID40, ResourceManager.GreenGraphicsID41, null, null, null, null, null, null, null, null, null, ResourceManager.GreenGraphicsID32, ResourceManager.GreenGraphicsID33, null]
					,[null, ResourceManager.GreenGraphicsID48, ResourceManager.GreenGraphicsID49, null, null, null, null, null, null, null, null, null, ResourceManager.GreenGraphicsID40, ResourceManager.GreenGraphicsID41, null]
					,[null, null, null, null, null, null, null, null, null, null, null, null, ResourceManager.GreenGraphicsID48, ResourceManager.GreenGraphicsID49, null]
					,[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]
					,[ResourceManager.GreenGraphicsID13, ResourceManager.GreenGraphicsID13, ResourceManager.GreenGraphicsID14, ResourceManager.GreenGraphicsID14, ResourceManager.GreenGraphicsID13, ResourceManager.GreenGraphicsID13, ResourceManager.GreenGraphicsID14, ResourceManager.GreenGraphicsID14, ResourceManager.GreenGraphicsID13, ResourceManager.GreenGraphicsID14, ResourceManager.GreenGraphicsID13, ResourceManager.GreenGraphicsID14, ResourceManager.GreenGraphicsID13, ResourceManager.GreenGraphicsID13, ResourceManager.GreenGraphicsID13]
					,[ResourceManager.GreenGraphicsID19, ResourceManager.GreenGraphicsID19, ResourceManager.GreenGraphicsID20, ResourceManager.GreenGraphicsID20, ResourceManager.GreenGraphicsID19, ResourceManager.GreenGraphicsID19, ResourceManager.GreenGraphicsID20, ResourceManager.GreenGraphicsID20, ResourceManager.GreenGraphicsID19, ResourceManager.GreenGraphicsID20, ResourceManager.GreenGraphicsID19, ResourceManager.GreenGraphicsID20, ResourceManager.GreenGraphicsID19, ResourceManager.GreenGraphicsID19, ResourceManager.GreenGraphicsID19]
					,[ResourceManager.GreenGraphicsID37, ResourceManager.GreenGraphicsID36, ResourceManager.GreenGraphicsID37, ResourceManager.GreenGraphicsID37, ResourceManager.GreenGraphicsID37, ResourceManager.GreenGraphicsID37, ResourceManager.GreenGraphicsID37, ResourceManager.GreenGraphicsID36, ResourceManager.GreenGraphicsID37, ResourceManager.GreenGraphicsID36, ResourceManager.GreenGraphicsID37, ResourceManager.GreenGraphicsID36, ResourceManager.GreenGraphicsID37, ResourceManager.GreenGraphicsID36, ResourceManager.GreenGraphicsID37]
					,[ResourceManager.GreenGraphicsID45, ResourceManager.GreenGraphicsID44, ResourceManager.GreenGraphicsID45, ResourceManager.GreenGraphicsID45, ResourceManager.GreenGraphicsID45, ResourceManager.GreenGraphicsID45, ResourceManager.GreenGraphicsID45, ResourceManager.GreenGraphicsID44, ResourceManager.GreenGraphicsID45, ResourceManager.GreenGraphicsID44, ResourceManager.GreenGraphicsID45, ResourceManager.GreenGraphicsID44, ResourceManager.GreenGraphicsID45, ResourceManager.GreenGraphicsID44, ResourceManager.GreenGraphicsID45]
					,[ResourceManager.GreenGraphicsID53, ResourceManager.GreenGraphicsID52, ResourceManager.GreenGraphicsID53, ResourceManager.GreenGraphicsID53, ResourceManager.GreenGraphicsID53, ResourceManager.GreenGraphicsID53, ResourceManager.GreenGraphicsID53, ResourceManager.GreenGraphicsID52, ResourceManager.GreenGraphicsID53, ResourceManager.GreenGraphicsID52, ResourceManager.GreenGraphicsID53, ResourceManager.GreenGraphicsID52, ResourceManager.GreenGraphicsID53, ResourceManager.GreenGraphicsID52, ResourceManager.GreenGraphicsID53]
					,[null, null, null, null, null, ResourceManager.GreenGraphicsID56, ResourceManager.GreenGraphicsID57, ResourceManager.GreenGraphicsID58, null, null, null, null, null, null, null]
					,[null, null, null, null, null, ResourceManager.GreenGraphicsID59, ResourceManager.GreenGraphicsID60, ResourceManager.GreenGraphicsID61, null, ResourceManager.GreenGraphicsID56, ResourceManager.GreenGraphicsID57, ResourceManager.GreenGraphicsID58, null, null, null]
					,[null, null, null, null, null, ResourceManager.GreenGraphicsID62, ResourceManager.GreenGraphicsID63, ResourceManager.GreenGraphicsID64, null, ResourceManager.GreenGraphicsID59, ResourceManager.GreenGraphicsID60, ResourceManager.GreenGraphicsID61, null, null, null]
					,[null, ResourceManager.GreenGraphicsID56, ResourceManager.GreenGraphicsID57, ResourceManager.GreenGraphicsID58, null, null, null, null, null, ResourceManager.GreenGraphicsID62, ResourceManager.GreenGraphicsID63, ResourceManager.GreenGraphicsID64, null, null, null]
					,[null, ResourceManager.GreenGraphicsID59, ResourceManager.GreenGraphicsID60, ResourceManager.GreenGraphicsID61, null, null, null, null, null, null, null, ResourceManager.GreenGraphicsID56, ResourceManager.GreenGraphicsID57, ResourceManager.GreenGraphicsID58, null]
					,[null, ResourceManager.GreenGraphicsID62, ResourceManager.GreenGraphicsID63, ResourceManager.GreenGraphicsID64, null, ResourceManager.GreenGraphicsID56, ResourceManager.GreenGraphicsID57, ResourceManager.GreenGraphicsID58, null, null, null, ResourceManager.GreenGraphicsID59, ResourceManager.GreenGraphicsID60, ResourceManager.GreenGraphicsID61, null]
					,[null, null, null, null, null, ResourceManager.GreenGraphicsID59, ResourceManager.GreenGraphicsID60, ResourceManager.GreenGraphicsID61, null, null, null, ResourceManager.GreenGraphicsID62, ResourceManager.GreenGraphicsID63, ResourceManager.GreenGraphicsID64, null]
					,[null, null, ResourceManager.GreenGraphicsID56, ResourceManager.GreenGraphicsID57, ResourceManager.GreenGraphicsID58, ResourceManager.GreenGraphicsID62, ResourceManager.GreenGraphicsID63, ResourceManager.GreenGraphicsID64, null, null, null, null, null, null, null]
					,[null, null, ResourceManager.GreenGraphicsID59, ResourceManager.GreenGraphicsID60, ResourceManager.GreenGraphicsID61, ResourceManager.GreenGraphicsID56, ResourceManager.GreenGraphicsID57, ResourceManager.GreenGraphicsID58, null, ResourceManager.GreenGraphicsID32, ResourceManager.GreenGraphicsID33, null, null, null, null]
					,[null, null, ResourceManager.GreenGraphicsID62, ResourceManager.GreenGraphicsID63, ResourceManager.GreenGraphicsID64, ResourceManager.GreenGraphicsID59, ResourceManager.GreenGraphicsID60, ResourceManager.GreenGraphicsID61, null, ResourceManager.GreenGraphicsID40, ResourceManager.GreenGraphicsID41, null, null, null, null]
					,[null, null, null, null, null, ResourceManager.GreenGraphicsID62, ResourceManager.GreenGraphicsID63, ResourceManager.GreenGraphicsID64, null, ResourceManager.GreenGraphicsID48, ResourceManager.GreenGraphicsID49, null, null, null, null]
					,[null, null, null, ResourceManager.GreenGraphicsID32, ResourceManager.GreenGraphicsID33, null, null, ResourceManager.GreenGraphicsID32, ResourceManager.GreenGraphicsID33, null, null, null, ResourceManager.GreenGraphicsID56, ResourceManager.GreenGraphicsID57, ResourceManager.GreenGraphicsID58]
					,[null, null, null, ResourceManager.GreenGraphicsID40, ResourceManager.GreenGraphicsID41, null, null, ResourceManager.GreenGraphicsID40, ResourceManager.GreenGraphicsID41, null, null, null, ResourceManager.GreenGraphicsID59, ResourceManager.GreenGraphicsID60, ResourceManager.GreenGraphicsID61]
					,[null, null, null, ResourceManager.GreenGraphicsID48, ResourceManager.GreenGraphicsID49, null, null, ResourceManager.GreenGraphicsID48, ResourceManager.GreenGraphicsID49, null, null, null, ResourceManager.GreenGraphicsID62, ResourceManager.GreenGraphicsID63, ResourceManager.GreenGraphicsID64]
				]
			];						
											
			addLevelEvent(
				new LevelEvent(
					1,
					function():void {objectFactory.getEnemy().startupBasicEnemy(
						ResourceManager.SmallGreenPlaneGraphics,
						new Point(100, -ResourceManager.SmallGreenPlaneGraphics.bitmap.height),
						50 + MathUtils.randomInteger(0, 100));}));
			
			addLevelEvent(
				new LevelEvent(
					3,
					function():void 
					{
						for each (var xPos:int in [150, 350])
						{
							objectFactory.getEnemy().startupBasicEnemy(
								ResourceManager.SmallGreenPlaneGraphics,
								new Point(xPos, -ResourceManager.SmallGreenPlaneGraphics.bitmap.height),
								50 + MathUtils.randomInteger(0, 100));
						}
					}
				));
			
			addLevelEvent(
				new LevelEvent(
					5,
					function():void {objectFactory.getEnemy().startupBasicEnemy(
						ResourceManager.SmallGreenPlaneGraphics,
						new Point(500, -ResourceManager.SmallGreenPlaneGraphics.bitmap.height),
						50 + MathUtils.randomInteger(0, 100));}));
		}

		
	}
}